#!/bin/sh
# nearly web app starter
export DB_URL=mongodb://localhost:27017/miprojekt
export MAPBOX_TOKEN=...
export JWT_SECRET=...
export PUBLIC_VAPID_KEY=...
export PRIVATE_VAPID_KEY=...
npm install
npm run build
npm start